import random
random.seed(2)
a = random.random()
print(a)
b = random.uniform(1, 10)
print(b)
c = random.randint(1,10)
print(c)
d = random.randrange(1, 10)
print(d)
e = random.normalvariate(0, 1)
print(e)
l = list('abhsnxkk')
f = random.choice(l)
print(f)
g = random.sample(l, 3)
print(g)
h = random.choices(l, k=3)
print(h)
random.shuffle(l)
print(l)
random.seed(1)
print(random.random())
print(random.randint(1, 10))